### ISSUE TITLE
Uploaded numbers with decimals are rounded in the download, the decimals should be available

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-tools-dev/EggsAndLarvae#10]
•	FlowMeter Int. Calibration is a rounded number in the down load, it is quite important that the uploaded decimals are also available in the down load
•	VolumeFiltInt is a rounded number, it would be good to have some decimals for this number as well

**Comment by CindyvanDamme** [comment]
These numbers are still rounded in the download

**Comment by cmspinto** [comment]
Hi Adriana, We need to check with a file in the upload to check why the numbers get rounded.
