### ISSUE TITLE
Update the EggsAndLarvae WebAPI

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/EggsAndLarvae#19]
List of the services

- [x] create a service to download the Historical Dataset

- [x] create a service to download the EM data

- [x] create a service to download the EH data

- [x] create a service to view summary of the data

**Comment by cmspinto** [comment]
Services are now created and the result is given in JSON (text format).

this should be easy to import to R.

@CindyvanDamme, do you know who can test the new webservices? Maybe Norbert or Matthias? (Just missing their GitHub user name)

The examples are [here](https://eggsandlarvae.ices.dk/Webservices.aspx) and any comments are more than welcome.

this is how to get the EH record:[https://eggsandlarvae.ices.dk/api/getEggsAndLarvaeDataEH?YearBegining=2018]( https://eggsandlarvae.ices.dk/api/getEggsAndLarvaeDataEH?YearBegining=2018)
how to get the EM record: [https://eggsandlarvae.ices.dk/api/getEggsAndLarvaeDataEH?YearBegining=2018](https://eggsandlarvae.ices.dk/api/getEggsAndLarvaeDataEH?YearBegining=2018)

**Comment by CindyvanDamme** [comment]
Looking good. Good idea to ask Matthias or Norbert, or maybe Brendan for testing.

Had a look myself and ran into these things:
- First time I tried to open the WSDL it gave an error message, second time it worked
- getEggsAndLarvaeDataSummary(): the 'Example to get the summary for the species Clupea Harengus' doesn't work
- getEggsAndLarvaeData(): the 'Example to get the data for the year of 1956' doesn't work
- getEggsAndLarvaeData(): the 'Example to get the data for the species Clupea Harengus for the year of 1998' doesn't work
- getEggsAndLarvaeDataEM(): I suppose the second 'Example to get the data from 2018'  should read 'Example to get the data from 2018 for the species Clupea harengus'

This is the error message I receive for the links that do not work:
![image](https://user-images.githubusercontent.com/26767282/103538675-f2c52780-4e96-11eb-83f6-20ea38a7bdd1.png)
