### ISSUE TITLE
Update Fact sheet in the Eggs and Larvae web site

### ISSUE THREAD

**Issue by odontaster** [ices-tools-dev/EggsAndLarvae#2]
This document was last updated in 2013:
http://ices.dk/marine-data/Documents/EggsandLarvae/EggsAndLarvaeDataset.pdf

**Comment by KloppmannMH** [comment]
is there an editable word file of this document (EggsAndLarvaeDataset.pdf). The document needs several updates and survey additions.

**Comment by norbert66** [comment]
I have prepared a word-version of the old text. We can start from there on, formatting will be done afterwards.

[EggsAndLarvaeDataset.docx]
(https://github.com/ices-tools-dev/EggsAndLarvae/files/4995024/EggsAndLarvaeDataset.docx)
