### ISSUE TITLE
Points on land

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/EggsAndLarvae#21]
Coordinates on land

The Working Group on North Sea Cod and Plaice Egg Surveys presents 212 events occurring on land. While some are close to an estuary or a lagoon and these are ok, many of them seem to be completely on land.

![image](https://user-images.githubusercontent.com/8705477/99390014-3b6d5500-28d8-11eb-8c98-7a99d43dfcd0.png)

**Comment by cmspinto** [comment]
We will put a list of the files that have point on land

**Comment by cmspinto** [comment]
[EggsAndlArvaeDataOnLand.xlsx](https://github.com/ices-tools-dev/EggsAndLarvae/files/5642716/EggsAndlArvaeDataOnLand.xlsx)

This is the summary of all point in land

**Comment by pcrjoana** [comment]
There are four surveys with points on land- MEGGS, EGGS, IHLS, and EEL.
Progress is under way regarding the MEGGS.
Norbert Rohlf was contacted about the IHLS.

[EggsAndLarvaePointsOnLand_EEL.xlsx](https://github.com/ices-tools-dev/EggsAndLarvae/files/5820372/EggsAndLarvaePointsOnLand_EEL.xlsx)
[EggsAndLarvaePointsOnLand_WGMEGGS.xlsx](https://github.com/ices-tools-dev/EggsAndLarvae/files/5820373/EggsAndLarvaePointsOnLand_WGMEGGS.xlsx)
[EggsAndLarvaePointsOnLand_WGEGGS.xlsx](https://github.com/ices-tools-dev/EggsAndLarvae/files/5820374/EggsAndLarvaePointsOnLand_WGEGGS.xlsx)
[EggsAndLarvaePointsOnLand_IHLS.xlsx](https://github.com/ices-tools-dev/EggsAndLarvae/files/5820375/EggsAndLarvaePointsOnLand_IHLS.xlsx)
