### ISSUE TITLE
Sometimes when filtering by year in the map it does not show any survey

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/EggsAndLarvae#22]

**Comment by colinpmillar** [comment]
I managed to replicate by 
* select year: 2019 -> "view changes on map"
* select survey: IHLS -> "view changes on map"
* select survey: All -> "view changes on map"

and now on the map I can see MEGS and IHLS, but on the survey drop down I cannot see MEGS, only IHLS.

**Comment by cmspinto** [comment]
I have followed the steps and it looks good to me. This could have been a survey code issue.
