### ISSUE TITLE
Add MIK NL 2020 data again to the database.

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/EggsAndLarvae#27]
I have re-upload the MIK data for NL in 2020. 
For some reason the first upload only uploaded the data until Sample. did not upload the measurements. 
We need to try to upload the file again to see if we can find what was the issue.

**Comment by CindyvanDamme** [comment]
After discovering an issue with empty rows, the NL MIK 2020 data was re-uploaded
