### ISSUE TITLE
Add filter by survey to the Eggs and Larvae selection in the Data portal

### ISSUE THREAD

**Issue by odontaster** [ices-tools-dev/EggsAndLarvae#28]
![image](https://user-images.githubusercontent.com/18613829/140925718-f37845be-7f39-4d44-8ac6-3b92f8a75ade.png)

**Comment by cmspinto** [comment]
Survey is added to the filters in data portal.
Tomorrow the service will be refreshed and it should be available soon.

**Comment by mehdiabbasi** [comment]
Hi @cmspinto @odontaster, I loaded EggsAndLarvae data on Data portal again and the survey is now on the Data criteria list. I just wondering why PlatformId is 0 in all data?
