### ISSUE TITLE
Empty hauls (no eggs or larvae) do not appear in the down load

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-tools-dev/EggsAndLarvae#3]
Dutch IHLS 2019 data were uploaded to the E&L database. When down loading the data from the database the empty hauls, containing no larvae, were missing from the data file

**Comment by cmspinto** [comment]
The empty hauls appear now in the map. We have to check the download but from the talk I had with Cindy I think the empty hauls are appearing in the download

**Comment by CindyvanDamme** [comment]
Empty hauls do appear on the map and in the down load
