### ISSUE TITLE
Add a new description to the MIK survey

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/EggsAndLarvae#30]
In this page: https://www.ices.dk/data/data-portals/Pages/Eggs-and-larvae.aspx

The MIK description:
![image](https://user-images.githubusercontent.com/8705477/145541582-722ee85e-15fd-4202-a333-42796a86cfe8.png)

Should be updated to this one:
**The midwater ring-net sampling during the 1st quarter IBTS in the North Sea (MIK-survey)**

The MIK-survey is carried out during night time since 1977 alongside the 1st quarter IBTS in the North Sea, eastern Channel, Kattegat and Skagerrak, and aims at large (> 18 mm standard length) herring larvae. It provides an abundance estimate of pre-recruits of the autumn spawning stock components of North Sea herring, which is used in the assessment as a recruitment index. The database contains quality checked data on length and abundance of herring larvae since 1992. In the most recent years, also data on other larval species such as sardine, sprat and lemon sole have been added. The ICES group responsible for the data is WGSINS.

**Comment by neil-ices-dk** [comment]
ok, will make a note to do it; @cmspinto is there an accompanying ISO19115 record that needs to be updated?

**Comment by KloppmannMH** [comment]
The MIK text should be added to the website. It shouldn't replace the description of the Mackerel and Horse mackerel egg survey (MEGS) as suggested here!
However, the MEGS text would need an update, too: the time frame is now 1992-2019. And data should be available until 2019, too. But check this in the database!

**Comment by neil-ices-dk** [comment]
Hi both the text on the landing page is already over long, suggest all text (for surveys) is reviewed and shortened and we refer to full meta data records for each survey where more descriptive information can be added.

**Comment by KloppmannMH** [comment]
I agree, that it could look a bit more like on DATRAS, where there is only a short summary on which data are available and which data products can be supplied. Though it looks like an easy task to produce a new text here, it must be agreed by the data providers, which could be the more difficult task. Or this could be handled through WGALES, which is a kind of super group for the ichthyoplankton survey.

**Comment by neil-ices-dk** [comment]
> Or this could be handled through WGALES

I think the supergroup approach would be the way to go - and i agree that the data providers need to be in control of this one

**Comment by KloppmannMH** [comment]
How do we do this. Shall we contact the chairs of WGALES for this (I could take care of this)?

**Comment by neil-ices-dk** [comment]
Yes Matthias, if you could initiate this, we can then follow-up with more specifics as needed 👍
