### ISSUE TITLE
ELDB Vocab: Use of ES-PV

### ISSUE THREAD

**Issue by odontaster** [ices-tools-dev/EggsAndLarvae#45]
There might be some challenges when registering in AIMS as it is not the same category of ISO as country. Need to check with submitter if this is still required, as EDMO guarantees independent submissions from different institutions.

**Comment by odontaster** [comment]
WGELFADG agreed to change all ES-PV to ES, as EDMO code exists to make sure Basque country submissions can be identified.

**Comment by cmspinto** [comment]
Done, the ES-PV fiels were changes ES.

**Comment by odontaster** [comment]
Also implemented in AIMS, the key has been changed to ES.
In the case title it remains ES-PV but I think it is good to leave it as it allows to trace this change in time without affecting possible submissions analysis etc

**Comment by MariaMakri** [comment]
Add an error that ES-PV is not allowed, only ES.
