### ISSUE TITLE
EM fields that can be uploaded to the E&L database do not appear in the downloaded file

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-tools-dev/EggsAndLarvae#5]
•	Length field, Subfactor are empty in the downloaded file
•	DevScale, DevStage are missing in the download
•	OilGlobulesFlag  will need to be linked to ‘Oil globules present’, is in the current download an empty field

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/74731114-b3bec100-5247-11ea-9764-1d9818cd3d36.png)


Need an example, looks like they are there?
