### ISSUE TITLE
Field names in the upload format are not the same in the down load format, also en lot of fields appear in the download format that cannot be uploaded

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-tools-dev/EggsAndLarvae#6]
It is necessary to update the download format in line with the upload format, and keeping in mind the format of the historic data already in the E&L database

**Comment by cmspinto** [comment]
The download format is inline with the download format. 

For the historical data, re-submission can be one way of aligning the data. 
It is not possible to automatically convert the data from an old format to the new format in the database!
