### ISSUE TITLE
What is the difference in the download format between Latitude/Longitude and HaulLat/HaulLon.

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-tools-dev/EggsAndLarvae#7]
The upload format has StartLatitude and StartLongitude the downlaod format had both Latitude/Longitude and HaulLat/HaulLon. The last two fields are empty in our downloaded file when downloading the Dutch IHLS 2019 data

**Comment by cmspinto** [comment]
Is this in the historical format?
