### ISSUE TITLE
Why is reworking of the uploaded HaulID and NationalHaulID happening and is this necessary

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-tools-dev/EggsAndLarvae#8]
Apparently in the uploaded HaulID and NationalHaulID are reworked to the downloaded Haulnumber and SampleNumber that makes it difficult to check with the original uploaded data. Why does this happen and  how is the uploaded data reworked and is this necessary?

**Comment by cmspinto** [comment]
Is it about these two: 
![image](https://user-images.githubusercontent.com/8705477/74731300-000a0100-5248-11ea-8cd0-9547f01ffc13.png)

We are not changing them in the upload!
