### ISSUE TITLE
EH fields are empty in the downloaded file, despite being uploaded and upload fields are linked to the wrong download field

### ISSUE THREAD

**Issue by CindyvanDamme** [ices-tools-dev/EggsAndLarvae#9]
•	Country, Haul Duration, FlowMeter Ext. Calibration, Max Sampling Depth, Bottom salinity are empty
•	Institute, GearDeployment, MeshType, CodendMesh, ELHaulFlag, NetopeningArea, NetClogging, FlowmeterType, FlowmeterBrand, ELVolFlag, DepthUpper are missing in the download
•	FlowEfficiency is missing, there is a field ‘Gear Efficiency’ in the download, but this is empty.
•	Volume Filter External is not provided in the upload
•	Water Depth is empty, which is actually BottomDepth in the upload
•	Haul Depth is all ‘0’. This field seems to be the uploaded DepthUpper, but should actually be the uploaded DepthLower
•	Which uploaded field becomes Temp max sampler depth? It is either the uploaded SurTemp or BotTemp but I can’t check that as the second decimal is missing in the down load. Can this down load field name be changed, so it is clear which original field it is?
•	I assume Salinity in the download is the uploaded SurSal, but this is unclear at the moment, can this download field name be changed?

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/74730973-6cd0cb80-5247-11ea-9e7d-9af5fa33102b.png)


Not for the download in the new format EM.
